---
functional:
  - Вход в систему с использованием учетных данных
  - Есть возможность восстановление пароля
  - Есть возможность использования сторонних сервисов для авторизации (github, discord)
  - Шапка должна содержать логотип и название сайта. Логотип является ссылкой на главную страницу сайта
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Смена языка на странице не должна влиять на расположение и дизайн блоков 
  - Должна быть функция выбора количества товара при добавлении в корзину
  - При клике по кнопке продолжить покупки переход обратно в магазин товаров происходит без перезагрузки страницы 
